name: Semgrep AppSec

on:
  workflow_dispatch:
  # 'push' scans the branch for the dashboard
  push:
    branches: [ "main", "codeql-testing", "semgrep-testing" ]
  # 'pull_request' triggers the inline PR comments
  pull_request:
    branches: [ "main", "codeql-testing", "semgrep-testing" ]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    # Necessary permissions for Semgrep to interact with your PR
    permissions:
      contents: read
      pull-requests: write # REQUIRED for comments
      security-events: write # For the 'Security' tab

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep CI
        run: semgrep ci
        env:
          # This token is what enables PR comments and the dashboard
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}